import { Category, Product, Order } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Vêtements', emoji: '👗', slug: 'clothing' },
  { id: '2', name: 'Casquettes', emoji: '🧢', slug: 'caps' },
  { id: '3', name: 'Robes', emoji: '🩱', slug: 'robes' },
  { id: '4', name: 'Maquillage', emoji: '💄', slug: 'makeup' },
  { id: '5', name: 'Maison', emoji: '🏠', slug: 'homeware' },
];

export const products: Product[] = [
  // Clothing
  {
    id: 'p1',
    name: 'T-Shirt Logo Oversize',
    category: 'clothing',
    price: 45,
    emoji: '👕',
    description: 'T-shirt oversize drop-shoulder avec logo TSKA brodé. 100% coton biologique.',
    badge: 'NEW',
    inStock: true,
    stock: 12,
  },
  {
    id: 'p2',
    name: 'Pantalon Large Cargo',
    category: 'clothing',
    price: 89,
    emoji: '👖',
    description: 'Pantalon cargo ample avec poches utilitaires. Essentiel du streetwear, barcha stylé.',
    badge: null,
    inStock: true,
    stock: 8,
  },
  {
    id: 'p3',
    name: 'Top Résille Superposé',
    category: 'clothing',
    price: 38,
    emoji: '🩹',
    description: 'Top en résille transparente, parfait à superposer sur un bralette ou body.',
    badge: 'HOT',
    inStock: true,
    stock: 3,
  },
  // Caps
  {
    id: 'p4',
    name: 'Casquette Classique Tska',
    category: 'caps',
    price: 35,
    emoji: '🧢',
    description: 'Casquette 6 panneaux structurée avec logo TSKA brodé. Taille unique.',
    badge: 'NEW',
    inStock: true,
    stock: 15,
  },
  {
    id: 'p5',
    name: 'Casquette Dad Hat Délavée',
    category: 'caps',
    price: 30,
    emoji: '🎩',
    description: 'Casquette déstructurée en coton délavé avec sangle réglable. Look vintage.',
    badge: null,
    inStock: true,
    stock: 7,
  },
  {
    id: 'p6',
    name: 'Bob Réversible',
    category: 'caps',
    price: 28,
    emoji: '🪣',
    description: 'Bob réversible classique en deux coloris. Incontournable de l\'été!',
    badge: null,
    inStock: true,
    stock: 20,
  },
  // Robes
  {
    id: 'p7',
    name: 'Robe Kimono en Satin',
    category: 'robes',
    price: 110,
    emoji: '🩱',
    description: 'Kimono satiné luxueux avec larges manches. Parfait pour se détendre ou offrir.',
    badge: 'HOT',
    inStock: true,
    stock: 5,
  },
  {
    id: 'p8',
    name: 'Robe Oversize en Polaire',
    category: 'robes',
    price: 95,
    emoji: '🥻',
    description: 'Robe en polaire ultra-douce avec grandes poches et capuche oversize.',
    badge: null,
    inStock: true,
    stock: 9,
  },
  // Makeup
  {
    id: 'p9',
    name: 'Set Lèvres Teinté',
    category: 'makeup',
    price: 25,
    emoji: '💄',
    description: 'Set trois pièces de gloss teinté en nudes rosés. Formule hydratante.',
    badge: null,
    inStock: true,
    stock: 25,
  },
  {
    id: 'p10',
    name: 'Illuminateur Glow',
    category: 'makeup',
    price: 38,
    emoji: '✨',
    description: 'Highlighter pressé modulable. Teintes or rose et champagne.',
    badge: 'HOT',
    inStock: true,
    stock: 18,
  },
  // Homeware
  {
    id: 'p11',
    name: 'Taie d\'Oreiller en Soie',
    category: 'homeware',
    price: 42,
    emoji: '🛋️',
    description: 'Taie d\'oreiller en soie de mûrier Grade 6A. Douce pour les cheveux et la peau.',
    badge: 'NEW',
    inStock: true,
    stock: 2,
  },
  {
    id: 'p12',
    name: 'Diffuseur à Roseaux',
    category: 'homeware',
    price: 35,
    emoji: '🕯️',
    description: 'Diffuseur artisanal à roseaux en parfums Black Rose et Vanilla Cloud.',
    badge: null,
    inStock: true,
    stock: 11,
  },
];

export const sampleOrders: Order[] = [
  {
    id: 'ORD-001',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    customer: { name: 'Sara Ben', email: 'sara@example.com', address: '123 Rue de la Paix', city: 'Tunis', phone: '+216 12 345 678' },
    items: [{ product: products[0], quantity: 1, size: 'M' }],
    subtotal: 45,
    shipping: 10,
    total: 55,
    status: 'Delivered',
  },
  {
    id: 'ORD-002',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    customer: { name: 'Mohamed Ali', email: 'ali@example.com', address: '456 Avenue Habib Bourguiba', city: 'Sfax', phone: '+216 98 765 432' },
    items: [{ product: products[3], quantity: 2 }, { product: products[8], quantity: 1 }],
    subtotal: 85,
    shipping: 10,
    total: 95,
    status: 'Processing',
  },
  {
    id: 'ORD-003',
    date: new Date().toISOString(),
    customer: { name: 'Fatima Mami', email: 'fatima@example.com', address: '789 Boulevard de l\'Indépendance', city: 'Sousse', phone: '+216 55 123 456' },
    items: [{ product: products[6], quantity: 1 }],
    subtotal: 110,
    shipping: 15,
    total: 125,
    status: 'Pending',
  },
];
